= SLF4J Utils

image:https://www.travis-ci.org/Koriit/slf4j-utils.svg?branch=master["Build Status", link="https://www.travis-ci.org/Koriit/slf4j-utils"]
image:https://www.codefactor.io/repository/github/koriit/slf4j-utils/badge[CodeFactor,link=https://www.codefactor.io/repository/github/koriit/slf4j-utils]
image:https://img.shields.io/badge/code%20style-%E2%9D%A4-FF4081.svg[ktlint,link=https://ktlint.github.io/]

image:https://api.bintray.com/packages/koriit/kotlin/slf4j-utils/images/download.svg[Download, link=https://bintray.com/koriit/kotlin/slf4j-utils/_latestVersion]
image:https://img.shields.io/github/license/koriit/slf4j-utils[GitHub]

SLF4J utils for Kotlin.

== Logger factory
With Kotlin lambdas, creating logger object can be as simple as `logger {}`.

Please, note that this function is opinionated. Logger name is fully qualified name of
class/file where logger object is defined.
This allows precise control over your loggers.

== Bridges
This library also includes bridges that intercept JUL, JCL and Log4J log statements and pass them to SLF4J.

This is handy as there are many libraries and frameworks that do not use SLF4J
and we usually want to see/control *all* of our logs.

== Fatal Logs
SLF4J has limited levels of logging and does not allow creating any custom levels.
Developers coming from many backgrounds tend to notice that certain errors -
a.k.a. FATAL - are more important than the other and require faster reaction.

According to SLF4J's http://www.slf4j.org/faq.html#fatal[FAQ]:
[quote]
The Marker interface, part of the org.slf4j package, renders the FATAL level largely redundant. If a given error requires attention beyond that allocated for ordinary errors, simply mark the logging statement with a specially designated marker which can be named "FATAL" or any other name to your liking.

However, preparing such marker and adding it to every fatal error can be a bit of tedious.
Thus this library provides a set of `fatal` extension functions that do this for you.

[WARNING]
Fatal logs are still logged as `ERROR`. Whether this difference is visible in the
output depends on your format, if it includes markers in some way.

== Exception Handling
This library provides `watch` and `watched` extension functions on the `Logger` to
create simple exception handler that just logs caught exception and eats it, or
shuts down the JVM.

It is useful in concurrent, long-lived workers, for example:

.Logger.watch
[source,kotlin]
----
private val LOG = logger {}

private val jobQueue = Channel<Job>(UNLIMITED)

private val worker = launch(correlated()) {
    with(LOG) {
        info("Started worker")
        watch(fatal = true) {
            for (job in jobQueue) {
                continueCorrelation((job as Continuation<*>).context) {
                    watch(ignore = listOf(MyCancellation::class)) {
                        job.await()
                    }
                }
            }
        }
        jobQueue.close()
        info("Closed worker")
    }
}
----

.Logger.watched
[source,kotlin]
----
// Ktor config
parentCoroutineContext += continueCorrelation() + LOG.watched(shutdown = true)
----

== Correlation

It may prove challenging to search for all logs related to particular process, especially
in applications which use any kind of concurrency as it leads to interleaving of logs.

To solve this issue it is possible to add special correlation id to logs which belong to the same process.

The easiest way to achieve that is using thread-local MDC provided by SLF4j.

However, it is a bit harder with Kotlin's coroutines as usually they are not bound to any specific thread during its execution.
Proper solution requires building correlated coroutine contexts.

Following functions ease building of said coroutine contexts and correlating threads in general.

=== Correlated
[source,kotlin]
----
// ...
// Threaded code (Correlation #1)
// ...

val job = launch(correlated()) {
    // (Correlation #2)
    while (isActive) {
        withCorrelation {
            // (Correlation #3)
        }
    }
    // (Correlation #2)
}

// ...
// Threaded code (Correlation #1)
// ...
----

=== SubCorrelated
[NOTE]
Sub-correlation can be nested only by one level. This is by design.

[source,kotlin]
----
// ...
// Threaded code (Correlation #1, no SubCorrelation)
// ...

val job = launch(subCorrelated()) {
    // (Correlation #1, SubCorrelation #1)
    while (isActive) {
        withSubCorrelation {
            // (Correlation #1, SubCorrelation #2)
        }
    }
    // (Correlation #1, SubCorrelation #2)
}

// ...
// Threaded code (Correlation #1, no SubCorrelation)
// ...
----

=== ContinueCorrelation
[source,kotlin]
----
// ...
// Threaded code (Correlation #1, no SubCorrelation)
// ...

val job = async(continueCorrelation(), start=LAZY) {
    // (Correlation #1, no SubCorrelation)
}

// ...
// Other threaded code (Correlation #2, no SubCorrelation)
// ...
launch(subCorrelated()) {
    // (Correlation #2, SubCorrelation #1)
    continueCorrelation((job as Continuation<*>).context) {
        // (Correlation #1, no SubCorrelation)
        val value = job.await()
        // (Correlation #1, no SubCorrelation)
    }
    // (Correlation #2, SubCorrelation #1)
}

----

=== ThreadCorrelation
[source,kotlin]
----
fun main() {
    // (no Correlation)
    val correlationId = correlateThread()
    // (Correlation #1)

    Thread {
        // (no Correlation)
        correlateThread(correlationId)
        // (Correlation #1)
    }.run()

    // (Correlation #1)

    Thread {
        // (no Correlation)
        subCorrelateThread(correlationId = correlationId)
        // (Correlation #1, SubCorrelation #1)
    }.run()

    // (Correlation #1)

    Thread {
        // (no Correlation)
        correlateThread()
        // (Correlation #2)
    }.run()

    // (Correlation #1)
    // ...
}
----
